### ISSUE TITLE
Remove all sold

### ISSUE THREAD

**Issue by jpaulodev** [futjs/fut-api#4]
I saw that the fut-api has the function deleteSoldFromTrade(), however it isn't in the README, do you know is secure to use this function?

The api is awesome with the bluebird promises! Good work bro!

**Comment by gregbarcza** [comment]
Yep It's safe, I didn't have the time to update Readme. I could use some help to maintain this repo, PR-s welcomed :)

**Comment by jpaulodev** [comment]
@barczaG good! I will try to help you.

In webapp we have an option to remove all the bids we didn't win. I checked the route and seems to be the same as **watchlist"" but passing the tradeIds in DELETE method, I don't know exaclty, I need to check it better to get the exact params of the request.

Could you check if it is possible to add this in fut-api? Or maybe I can create a fork of this repo, do some changes and let you check.
